
-- MySQL Script generated by MySQL Workbench
-- Fri Aug 11 13:51:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prueba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prueba` DEFAULT CHARACTER SET utf8 ;
USE `prueba` ;

-- -----------------------------------------------------
-- Table `prueba`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`consultas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `medico_id` BIGINT NOT NULL,
  `paciente_id` BIGINT NOT NULL,
  `data`DATETIME NOT NULL,

  PRIMARY KEY (`id`),

  CONSTRAINT fk_consultas_medicos_id FOREIGN KEY(`medico_id`) references medicos(`id`),
  CONSTRAINT fk_consultas_paciente_id FOREIGN KEY(`paciente_id`) references paciente(`id`),

)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;